#pragma once
#define GAME_DEFAULT_FONT_PATH "Resources/Fonts/ObliviousFont.ttf"
#define GAME_LOST_FONT_PATH "Resources/Fonts/TheyPerished.ttf"
#define GAME_WON_FONT_PATH "Resources/Fonts/Flyknit.ttf"
#define GAME_RESULT_FONT_PATH "Resources/Fonts/Flyknit.ttf"
#define GAME_BEST_RESULT_FONT_PATH "Resources/Fonts/ObliviousFont.ttf"
#define GAME_MENU_FONT_PATH "Resources/Fonts/Mf_July_Sky.ttf"
#define GAME_INFO_FONT_PATH "Resources/Fonts/Pamela_full.ttf"
#define GAME_INPUT_FONT_PATH "Resources/Fonts/Pamela_full.ttf"
#define GAME_OUTPUT_FONT_PATH "Resources/Fonts/ObliviousFont.ttf"